### ISSUE TITLE
Null pointer acception on gReq.DadConfig.ErrorStyle

### ISSUE THREAD

**Issue by JohannesKaranitsch** [mortenbra/thoth-gateway#2]
I tested compiling thoth-gateway with VS Cummunity 2015 and .NET Framework 4. Compiling worked so far, but get runtime error on first test. I had no rigth dad config and only accessed / of website, so it run into Line 336 PLSQLHttpModule.cs and I got an Null pointer acception on gReq.DadConfig.ErrorStyle, because gReq.DadConfig is not set. Of course because I used wrong URl, but error handling should work. Please contact me for discussing a solution and some ideas.
Otherwise very good work!
Thanx!

**Comment by mortenbra** [comment]
Fixed in upcoming v1.4.5 release.
