### ISSUE TITLE
Question regarding custom HTTP Header Variable

### ISSUE THREAD

**Issue by zMietek** [mortenbra/thoth-gateway#3]
Hi,

I'm using with help of Thoth Gateway old APEX installation with IIS server. Now developers wants to integrate own SSO solution in front of APEX application and asked me about if is possible to 
to configure Thoth Gateway to using custom HTTP header variable. The original SSO solution is using Oracle Application Server.

Documentation says:
=================
Make Oracle Aware of Custom HTTP Header Variable
Modify dads.conf file and create the following entry for HTTP_SCGID to the 
PLsqlCGIEnvironmentList.   

PlsqlCGIEnvironmentList HTTP_SCGID
=================

Is it enough on the side of Thoth Gateway to put into web.config file entries like this example?
<thoth>
		
		
		<dad name="apex">
			<params>
				<param name="CGIEnvironmentList" value="HTTP_SCGID" />
.....
			</params>
		</dad>
	</thoth>

Thank you in advance
Mietek

**Comment by mortenbra** [comment]
Hi Mietek, as noted in the description of the Thoth Gateway at https://github.com/mortenbra/thoth-gateway

"Override CGI environment variables in DAD configuration file. Note that the Thoth Gateway passes all CGI variables from the web server to OWA; by default mod_plsql passes just a subset and you have to add additional parameters in the DAD config file."

Which means you should not have to do anything to get access to the HTTP_SCGID variable as long as it is passed from the client or some middleware before being passed to the gateway.

**Comment by zMietek** [comment]
Hi,

thank you very much for clarifying words. Looks like easy job for me: doing nothing :)

Best regards
Mietek
