### ISSUE TITLE
Download BLOB Size Limitation?

### ISSUE THREAD

**Issue by joejan777** [mortenbra/thoth-gateway#7]
Hello, Using APEX 19/Windows 2016/THOTH GATEWAY, we are trying to download a 9GB blob to the client browser from the database.  It worked with a 1GB blob but fails with a 1.5GB blob test (the next smallest test size we have). We have set higher timeouts in IIS and connection times in the web.config. We are wondering if there is a limitation to the download size in the THOTH GATEWAY. We are seeing "Array dimensions exceeded supported range."  With the stack trace:
[OverflowException: Array dimensions exceeded supported range.]
Oracle.ManagedDataAccess.Types.OracleBlob.get_Value() +114
PLSQLGatewayModule.OracleInterface.GetDownloadFile (String fileType) +358
PLSQLGatewayModule.GatewayResponse.FetchOwaResponse(OracleInterface ora) +193
PLSQLGatewayModule.PLSQLHttpModule.HandleRequest(Object o, EventArgs a ) +4074
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +139
System.Web.HttpApplication.ExecuteStepImpl(ExecutionStep step) +195
System.Web.HttpApplication.ExecuteStep (IExecutionStep step, Boolean& completedSynchronously) +88

Any help is greatly appreciated!

**Comment by mortenbra** [comment]
It seems the error occurs in the Oracle Data Provider for .NET (ODP.NET, managed driver). Perhaps you can try to ask a general question about max blob sizes in the ODP.NET forums, hopefully one of the devs will respond:

https://community.oracle.com/tech/developers/categories/odp.net
