### ISSUE TITLE
Basic Authentication: How To

### ISSUE THREAD

**Issue by tomhillgreyridge** [mortenbra/thoth-gateway#9]
Hi there.

I'm trying out Thoth Gateway to replace ModPLSQL for some old web toolkit (non apex) applications that use Basic Auth.  The documentation says that Thoth supports basic auth but I can't see how to set it up from the documentation.

As an example, we have an application which currently has two parts - public and authenticated and looks like this

```
# Basic url for the application - uses basic authentication so will pop up a prompt
# for an oracle database user and password and use that for the connection
<Location /application/authenticated>
  SetHandler                    pls_handler
  PlsqlDatabaseConnectString    [database connect string]
  PlsqlAuthenticationMode       Basic
</Location>

# public access section - uses hard coded username / password
<Location /application/public>
  SetHandler                    pls_handler
  PlsqlDatabaseConnectString    [database connect string]
  PlsqlAuthenticationMode       Basic
  PlsqlDatabaseUsername         public_user
  PlsqlDatabasePassword         public_password
</Location>
```
Can this be replicated in Thoth and, if so, how?

Apologies if this is already documented - I did have a good look through the parameters but couldn't see anything specific.

**Comment by mortenbra** [comment]
Hi,

The Thoth Gateway had support for Basic Authentication prior to version 1.3.7, at which point it was removed.

From the Release Notes (see /doc/release-notes.htm in the download):

Version 1.3.7:

- DEPRECATED: Removed support for OWA.SET_USER_ID / OWA.SET_PASSWORD: Prior to version 1.3.7, the Thoth Gateway would call these OWA procedures during initialization of each request, and pass the HTTP Basic Authentication username and password (if any) to OWA, allowing these values to be referenced in OWA authorization checks. This is not required for typical Apex applications (and is not done by Oracle's own Apex Listener, either), and has therefore been removed from the Thoth Gateway.
